name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
            [System.Net.WebClient]::new().downloadFile("https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-9.0.0-msvcrt-r6/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r6.zip", "winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r6.zip")
            [System.IO.Compression.ZipFile]::ExtractToDirectory("winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r6.zip", "C:\") | Remove-Item
            echo "C:\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

            [System.Net.WebClient]::new().downloadFile("https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip", "ninja-win.zip")
            [System.IO.Compression.ZipFile]::ExtractToDirectory("ninja-win.zip", "C:\ninja") | Remove-Item
            echo "C:\ninja" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: make
