name: build

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          curl -L https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-14.0.0-9.0.0-ucrt-r7/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64ucrt-9.0.0-r7.zip -o winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64ucrt-9.0.0-r7.zip
          tar -xf winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64ucrt-9.0.0-r7.zip -C C:\
          Add-Content $env:GITHUB_PATH "C:\mingw64\bin"

      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          cmake . -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j
        env:
          CC: gcc
          CXX: g++

      - name: Set artifacts suffix (if tag)
        if: startsWith(github.ref, 'refs/tags/') == true
        run: Add-Content $env:GITHUB_ENV "git_suffix=$(git describe --tags --abbrev=0)"

      - name: Set artifacts suffix (if branch)
        if: startsWith(github.ref, 'refs/tags/') != true
        run: Add-Content $env:GITHUB_ENV "git_suffix=$(Write-Output "$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)")"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: minicom2-win-gcc11-${{env.git_suffix}}
          path: build/minicom2.exe
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install g++-11 ninja-build

      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          cmake . -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j
        env:
          CC: gcc-11
          CXX: g++-11

      - name: Set artifacts suffix (if tag)
        if: startsWith(github.ref, 'refs/tags/') == true
        run: echo "git_suffix=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Set artifacts suffix (if branch)
        if: startsWith(github.ref, 'refs/tags/') != true
        run: echo "git_suffix=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: minicom2-linux-gcc11-${{env.git_suffix}}
          path: build/minicom2
          if-no-files-found: error
